"""
deploy_client.py — Appian REST Deployment API Client

Uploads an Appian package ZIP to a live Appian environment using the
Deployment Management REST API v2.

API Reference:
    POST /suite/deployment-management/v2/deployments
    Headers:
        appian-api-key: <service-account-api-key>
        Action-Type: import
    Body: multipart/form-data
        - file: <zip binary>
        - name: <deployment name>

Usage:
    from appian_generator.deploy_client import AppianDeployClient

    client = AppianDeployClient(
        base_url="https://your-instance.appiancloud.com",
        api_key="your-service-account-api-key"
    )
    result = client.deploy("output/NCI_RB_package.zip", name="NCI RB Migration v1")
    print(result)
"""

import json
import time
from pathlib import Path

try:
    import urllib.request
    import urllib.parse
    import urllib.error
    HAS_URLLIB = True
except ImportError:
    HAS_URLLIB = False


class AppianDeployClient:
    """
    Client for Appian Deployment Management REST API v2.

    Requires a Service Account with an API Key configured in Appian Admin Console.
    The service account needs "Import" permission on the target environment.
    """

    API_BASE = "/suite/deployment-management/v2"
    DEPLOY_ENDPOINT = "/deployments"
    STATUS_ENDPOINT = "/deployments/{uuid}"

    def __init__(self, base_url: str, api_key: str, timeout: int = 300,
                 verify_ssl: bool = True):
        """
        Args:
            base_url: Appian environment URL (e.g. https://yourdomain.appiancloud.com)
            api_key: Service Account API Key from Appian Admin Console
            timeout: Max seconds to wait for deployment to complete (default 300)
            verify_ssl: Whether to verify SSL certificates (default True)
        """
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.timeout = timeout
        self.verify_ssl = verify_ssl

    def deploy(self, zip_path: str, name: str = "", description: str = "",
               verbose: bool = True) -> dict:
        """
        Upload and import an Appian package ZIP.

        Args:
            zip_path: Local path to the .zip file
            name: Deployment name (defaults to ZIP filename)
            description: Optional deployment description
            verbose: Print progress messages

        Returns:
            dict with deployment result including status and any errors
        """
        zip_file = Path(zip_path)
        if not zip_file.exists():
            return {"success": False, "error": f"File not found: {zip_path}"}

        if not name:
            name = f"NTT DATA Migration — {zip_file.stem}"
        if not description:
            description = f"Generated by NTT DATA IBM BPM → Appian pipeline"

        if verbose:
            print(f"\n🚀 Deploying to Appian...")
            print(f"   URL: {self.base_url}")
            print(f"   Package: {zip_file.name} ({zip_file.stat().st_size // 1024} KB)")
            print(f"   Name: {name}")

        # Build the deployment request
        result = self._post_deployment(zip_file, name, description)

        if not result.get("success"):
            return result

        deployment_uuid = result.get("deploymentUuid")
        if verbose:
            print(f"   ✓ Upload accepted. Deployment UUID: {deployment_uuid}")
            print(f"   ⏳ Waiting for deployment to complete...")

        # Poll for completion
        final = self._poll_status(deployment_uuid, verbose=verbose)
        return final

    def _post_deployment(self, zip_file: Path, name: str, description: str) -> dict:
        """POST the ZIP to create a new deployment."""
        url = f"{self.base_url}{self.API_BASE}{self.DEPLOY_ENDPOINT}"

        try:
            # Build multipart body manually
            boundary = "----AppianMigrationBoundary7788"
            body_parts = []

            # Add name field
            body_parts.append(
                f"--{boundary}\r\n"
                f'Content-Disposition: form-data; name="name"\r\n\r\n'
                f"{name}\r\n"
            )

            # Add description field
            body_parts.append(
                f"--{boundary}\r\n"
                f'Content-Disposition: form-data; name="description"\r\n\r\n'
                f"{description}\r\n"
            )

            # Add file field
            file_data = zip_file.read_bytes()
            file_header = (
                f"--{boundary}\r\n"
                f'Content-Disposition: form-data; name="file"; filename="{zip_file.name}"\r\n'
                f"Content-Type: application/zip\r\n\r\n"
            )
            closing = f"\r\n--{boundary}--\r\n"

            # Combine to bytes
            body = (
                "".join(body_parts).encode("utf-8") +
                file_header.encode("utf-8") +
                file_data +
                closing.encode("utf-8")
            )

            headers = {
                "appian-api-key": self.api_key,
                "Action-Type": "import",
                "Content-Type": f"multipart/form-data; boundary={boundary}",
                "Content-Length": str(len(body)),
            }

            req = urllib.request.Request(url, data=body, headers=headers, method="POST")

            # SSL context
            import ssl
            ctx = ssl.create_default_context() if self.verify_ssl else ssl._create_unverified_context()

            with urllib.request.urlopen(req, context=ctx, timeout=60) as resp:
                resp_body = resp.read().decode("utf-8")
                resp_data = json.loads(resp_body) if resp_body else {}
                deployment_uuid = (
                    resp_data.get("uuid") or
                    resp_data.get("deploymentUuid") or
                    resp.headers.get("Location", "").split("/")[-1]
                )
                return {"success": True, "deploymentUuid": deployment_uuid, "raw": resp_data}

        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            return {
                "success": False,
                "error": f"HTTP {e.code}: {e.reason}",
                "details": error_body[:500],
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def _poll_status(self, deployment_uuid: str, poll_interval: int = 5,
                     verbose: bool = True) -> dict:
        """Poll deployment status until completion or timeout."""
        url = f"{self.base_url}{self.API_BASE}{self.STATUS_ENDPOINT.format(uuid=deployment_uuid)}"
        elapsed = 0

        import ssl
        ctx = ssl.create_default_context() if self.verify_ssl else ssl._create_unverified_context()

        while elapsed < self.timeout:
            try:
                req = urllib.request.Request(url, headers={"appian-api-key": self.api_key})
                with urllib.request.urlopen(req, context=ctx, timeout=30) as resp:
                    data = json.loads(resp.read().decode("utf-8"))

                status = data.get("status", "UNKNOWN")

                if verbose:
                    print(f"   [{elapsed}s] Status: {status}")

                if status in ("COMPLETED", "SUCCESS", "DEPLOYED"):
                    if verbose:
                        print(f"\n   ✅ Deployment SUCCESSFUL!")
                    return {"success": True, "status": status, "deploymentUuid": deployment_uuid,
                            "raw": data}
                elif status in ("FAILED", "ERROR", "INVALID"):
                    errors = data.get("errors", data.get("message", "Unknown error"))
                    if verbose:
                        print(f"\n   ✗ Deployment FAILED: {errors}")
                    return {"success": False, "status": status, "error": str(errors),
                            "deploymentUuid": deployment_uuid, "raw": data}

                time.sleep(poll_interval)
                elapsed += poll_interval

            except Exception as e:
                if verbose:
                    print(f"   ⚠ Poll error: {e}")
                time.sleep(poll_interval)
                elapsed += poll_interval

        return {"success": False, "error": f"Timeout after {self.timeout}s",
                "deploymentUuid": deployment_uuid}

    @classmethod
    def from_env(cls) -> "AppianDeployClient":
        """Create client from environment variables APPIAN_URL and APPIAN_API_KEY."""
        import os
        url = os.environ.get("APPIAN_URL", "")
        key = os.environ.get("APPIAN_API_KEY", "")
        if not url or not key:
            raise ValueError("Set APPIAN_URL and APPIAN_API_KEY environment variables")
        return cls(base_url=url, api_key=key)
